### ISSUE TITLE
missing parameter

### ISSUE THREAD

**Issue by hblink** [menloparklab/falcon-langchain#1]
@cl.langchain_factory
     ^^^^^^^^^^^^^^^^^^^^
  File "/home/papa/.pyenv/versions/3.11.4/lib/python3.11/site-packages/chainlit/telemetry.py", line 77, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/papa/.pyenv/versions/3.11.4/lib/python3.11/site-packages/chainlit/__init__.py", line 93, in langchain_factory
    raise ValueError(error_message)
ValueError: langchain_factory use_async parameter is required

**Comment by painful-bug** [comment]
same error

**Comment by utmishra** [comment]
Submitted a [PR](https://github.com/menloparklab/falcon-langchain/pull/2) to resolve this.

**Comment by Risingabhi** [comment]
same error:

Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/chainlit", line 8, in <module>
    sys.exit(cli())
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/chainlit/cli/__init__.py", line 145, in chainlit_run
    run_chainlit(target)
  File "/home/codespace/.local/lib/python3.10/site-packages/chainlit/cli/__init__.py", line 46, in run_chainlit
    load_module(config.run.module_name)
  File "/home/codespace/.local/lib/python3.10/site-packages/chainlit/config.py", line 200, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/falcon-langchain/app.py", line 22, in <module>
    def factory():
  File "/home/codespace/.local/lib/python3.10/site-packages/chainlit/telemetry.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/chainlit/lc/__init__.py", line 38, in langchain_factory
    raise ValueError(error_message)
ValueError: langchain_factory use_async parameter is required

**Comment by developbyarya** [comment]
I solved by simply adding `use_async=False` in `langchain_factory `decorators

`@cl.langchain_factory(use_async=False) 
`
